name: Test

on:
  push:
    branches: [master, qe]
  pull_request:
    branches:  [master, qe]
  release:
    types: [published, edited]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the code
        run: echo "Test"
